import { AllureReporterExtensions } from "./allureReporterExtensions";
export { Gherkin } from "./gherkin";
export declare const getJasmineAllureReporter: typeof AllureReporterExtensions.getJasmineAllureReporter;
export declare const addArgument: typeof AllureReporterExtensions.addArgument;
export declare const addDescription: typeof AllureReporterExtensions.addDescription;
export declare const addEnvironment: typeof AllureReporterExtensions.addEnvironment;
export declare const attachScreenshot: typeof AllureReporterExtensions.attachScreenshot;
export declare const Step: typeof AllureReporterExtensions.Step;
export declare const DescribedStep: any;
export declare const addFeature: typeof AllureReporterExtensions.addFeature;
export declare const addStory: typeof AllureReporterExtensions.addStory;
export declare const createAttachment: typeof AllureReporterExtensions.createAttachment;
export declare const Heading: typeof AllureReporterExtensions.Heading;
export declare const ScreenedStep: typeof AllureReporterExtensions.ScreenedStep;
export declare const DescribedScreenedStep: any;
export declare const setScreenshotProvider: typeof AllureReporterExtensions.setScreenshotProvider;
